my_seq = 'GGTTAACTCGTAGCGATTGACATCAGTAGTACGATGACAGTACGTACATATAGCTAGATCGATTCGACTTCGATCGATCACTTACGACAGTCACGTACGTATCAGATCTAGATCGATCTCGATCGACTAG'
for i in range(len(my_seq)-4):
    print(my_seq[i:i+5])

print(my_seq)